[tool]
id = “scan” # need to be same as picoclie name in java file

[[dependency]]
# Shadow jar is required as it contains dependencies needed to run the sonar scanner methods in the bal scanner
path = "../build/libs/ScanCommand-1.0.jar"

# For including the custom rules JAR (For now this will be not consided)
# [[dependency]]
# path = "../../custom-rules-plugin/build/libs/custom-rules-plugin-1.0.jar"

# For including the SonarQube Platform JAR
[[dependency]]
path = "../../sonar-ballerina-plugin/build/libs/sonar-ballerina-plugin-1.0-all.jar"