[tool]
id = “scan” # need to be same as picoclie name in java file

[[dependency]]
path = "C:\\Users\\Tharana Wanigaratne\\Desktop\\sonar-ballerina\\ScanCommand\\build\\libs\\ScanCommand.jar" # tool jar file location