[package]
org = "tharana_wanigaratne"
name = "bal_scan_tool_tester"
version = "0.1.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

# Testing custom property retrieving from toml file
[scan]
# With absolute path
configPath = "C:/Users/Tharana Wanigaratne/Desktop/sonar-ballerina/ScanCommand/bal-scan-tool-tester/Scan.toml"

# With relative path
#configPath = "ScanCommand/bal-scan-tool-tester/Scan.toml"