[package]
org = "ballerina"
name = "bal_scan_tool_tester"
version = "0.1.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

# Testing custom property retrieving from toml file
[scan]
# With local file path
configPath = "Scan.toml"

# With remote path
#configPath = "https://raw.githubusercontent.com/Xenowa/sonar-ballerina/main/ScanCommand/bal-scan-tool-tester/Scan.toml"