# For platform specific properties to get picked up, the path should be valid
#[[platform]]
#name = "sonarqube"
#path = "https://github.com/SonarDance/remotePlatformPluginJARs/raw/main/sonar-platform-plugin-1.0.jar"

# TODO: Central repo and Local repo plugins should be definable as
#   Local repository plugins
#   [[analyzer]]
#   org = "tharana_wanigaratne"
#   name = "custom_static_code_analyzer"
#   version = "0.1.0"
#   repository = "local"
#   Central repository plugins ()
#   [[analyzer]]
#   org = "tharana_wanigaratne"
#   name = "custom_static_code_analyzer"

[[analyzer]]
org = "tharana_wanigaratne"
name = "custom_static_code_analyzer"
version = "0.1.0"

[rule]
include = ["S107", "S108", "S109"]
exclude = ["S107"]

# ================================================
# Invalid use cases which are ignored by scan tool
# ================================================
[[platform]]
name = ""
path = "https://github.com/SonarDance/remotePlatformPluginJARs/raw/main/sonarqube-platform-plugin-1.0.jar"

[[platform]]
name = 10
path = "https://github.com/SonarDance/remotePlatformPluginJARs/raw/main/sonarqube-platform-plugin-1.0.jar"

[[platform]]


[[analyzer]]
org = "org3"
name = "name3"
version = "version"

[[analyzer]]
org = ""
name = ""
version = ""
repository = ""

[[analyzer]]
org = 20
name = 10
version = 30
repository = 40

[[analyzer]]