# =========================================================
# all following are optional (populated with defaul values)
# =========================================================
[[platform]]
name = "sonarqube"
path = "C:\\Users\\Tharana Wanigaratne\\Desktop\\sonar-ballerina\\sonarqube-platform-plugin\\build\\libs\\sonarqube-platform-plugin-1.0.jar"

[[platform]]
name = "semgrep"
path = "C:\\Program Files\\Ballerina\\distributions\\ballerina-2201.8.5\\bre\\lib\\semgrep-ballerina-plugin-1.0-all.jar"

[[platform]]
name = "codeql"
path = "C:\\Program Files\\Ballerina\\distributions\\ballerina-2201.8.5\\bre\\lib\\codeql-ballerina-plugin-1.0-all.jar"


[[plugin]]
org = "org1"
name = "name1"
version = "version"

[[plugin]]
org = "org2"
name = "name2"
version = "version"

[[plugin]]
org = "org3"
name = "name3"
version = "version"


[[rule]]
id = "S107"

[[rule]]
id = "S108"

[[rule]]
id = "S109"