# For platform specific properties to get picked up, the path should be valid
#[[platform]]
#name = "sonarqube"
#path = "https://github.com/SonarDance/remotePlatformPluginJARs/raw/main/sonar-platform-plugin-1.0.jar"

# ballerina module compiler plugin
[[analyzer]]
org = "ballerina"
name = "io"
version = "1.5.0"

# ballerinax module compiler plugin
[[analyzer]]
org = "ballerinax"
name = "github"
version = "4.6.0"

# custom compiler plugin
[[analyzer]]
org = "tharana_wanigaratne"
name = "custom_rules_analyzer"

[rule]
include = [
    "B107",
    "B108",
    "ballerina/io:B109",
    "ballerinax/github:B109",
    "tharana_wanigaratne/custom_rules_analyzer:B109",
]
exclude = ["B107"]

# ================================================
# Invalid use cases which are ignored by scan tool
# ================================================
[[platform]]
name = ""
path = "https://github.com/SonarDance/remotePlatformPluginJARs/raw/main/sonarqube-platform-analyzer-1.0.jar"

[[platform]]
name = 10
path = "https://github.com/SonarDance/remotePlatformPluginJARs/raw/main/sonarqube-platform-analyzer-1.0.jar"

[[platform]]


[[analyzer]]
org = "org3"
name = "name3"
version = "version"

[[analyzer]]
org = ""
name = ""
version = ""
repository = ""

[[analyzer]]
org = 20
name = 10
version = 30
repository = 40

[[analyzer]]