# =========================================================
# all following are optional (populated with defaul values)
# =========================================================
[sonarqube]
# If the user has defined the sonar-projec.properties somewhere other than the working directory
sonarProjectPropertiesPath = "C:\\Users\\Tharana Wanigaratne\\Desktop\\sonar-ballerina\\ScanCommand\\bal-scan-tool-tester\\sonar-project.properties"
# If the user wants to have the platform plugin in somewhere which is not bre/libs
platformPluginPath = "C:\\Program Files\\Ballerina\\distributions\\ballerina-2201.8.2\\bre\\lib\\sonar-ballerina-plugin-1.0-all.jar"

[semgrep]
platformPluginPath = "C:\\Program Files\\Ballerina\\distributions\\ballerina-2201.8.2\\bre\\lib\\semgrep-ballerina-plugin-1.0-all.jar"

[codeql]
platformPluginPath = "C:\\Program Files\\Ballerina\\distributions\\ballerina-2201.8.2\\bre\\lib\\codeql-ballerina-plugin-1.0-all.jar"

# =====
# Notes
# =====
# The user can report to multiple platforms by running "bal scan --platform='sonarqube, semgrep, codeql'"
# or by mentioning the platforms as in this file and running "bal scan" only