# For platform specific properties to get picked up, the path should be valid
#[[platform]]
#name = "sonarqube"
#path = "https://github.com/SonarDance/remotePlatformPluginJARs/raw/main/sonarqube-platform-plugin-1.0.jar"
#sonarProjectPropertiesPath = "sonar-project.properties"

[[plugin]]
org = "tharana_wanigaratne"
name = "custom_static_code_analyzer"
version = "0.1.0"

[[plugin]]
org = "org3"
name = "name3"
version = "version"

[rule]
ids = "S107, S108"

# ================================================
# Invalid use cases which are ignored by scan tool
# ================================================
[[platform]]
name = ""
path = "https://github.com/SonarDance/remotePlatformPluginJARs/raw/main/sonarqube-platform-plugin-1.0.jar"

[[platform]]
name = 10
path = "https://github.com/SonarDance/remotePlatformPluginJARs/raw/main/sonarqube-platform-plugin-1.0.jar"

[[platform]]

[[plugin]]
org = ""
name = ""
version = ""
repository = ""

[[plugin]]
org = 20
name = 10
version = 30
repository = 40

[[plugin]]