name: Build

# Action Listeners
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Actions
jobs:
  ubuntu_build:
    name: Build with tests on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 120
    concurrency:
      group: ${{ github.head_ref }}-ubuntu
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.7'

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        # To make sure the scan command gets built before running tests
        run: |
          ./gradlew build

  windows_build:
    name: Build with tests on Windows
    runs-on: windows-latest
    timeout-minutes: 120
    concurrency:
      group: ${{ github.head_ref }}-windows
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.7'

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: '2201.9.0'

      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew.bat build