name: Build

# Action Listeners
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Actions
jobs:
  ubuntu_build:
    name: Build with tests on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 120
    concurrency:
      group: ${{ github.head_ref }}-ubuntu
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.7'

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew build

# Currently windows build is not possible due to issue: https://github.com/ballerina-platform/ballerina-action/issues/57
#  windows_build:
#    name: Build with tests on Windows
#    runs-on: windows-latest
#    timeout-minutes: 120
#    concurrency:
#      group: ${{ github.head_ref }}-windows
#      cancel-in-progress: true
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '17.0.7'
#
#      - name: Set Up Ballerina
#        uses: ballerina-platform/setup-ballerina@v1.1.0
#        with:
#          version: latest
#
#      - name: Build with Gradle
#        env:
#          packageUser: ${{ github.actor }}
#          packagePAT: ${{ secrets.GITHUB_TOKEN }}
#        run: ./gradlew.bat build