name: Publish release

# Action Listeners
on:
  workflow_dispatch:

# Actions
jobs:
  publish_release:
    name: Publish scan tool package to GitHub and Ballerina Central
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.7'

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build -x check -x test

      - name: publish artifacts to GitHub package registry
        env:
          publishUser: ${{ github.actor }}
          publishPAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish

      - name: Release package to Ballerina Central
        env:
          publishUser: ${{ github.actor }}
          publishPAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew release
